### ISSUE TITLE
Send File

### ISSUE THREAD

**Issue by masoodbayati** [unreg/actorbot#2]
We can't send File to our users by this sdk, am i true?

**Comment by unreg** [comment]
not quite.

Hint for any message, eg type "Document" (image, file etc):

```
from actorbot.api import BaseMessage
from actorbot.api import messaging

...

    message = BaseMessage(<dict_with_valid_message>)

    out_message = messaging.sendMessage(self._get_id(),
        peer=peer, message=message)
    await self.send(out_msg)
```

High level object such as _messaging.TextMessage_ not yet. In the plans.

Also has upload and download files:
https://github.com/unreg/actorbot/blob/master/actorbot/api/files.py

N.B. Just keep in mind that the current state SDK is unstable, and there will be changes in the functions and methods, such as _send_.

**Comment by masoodbayati** [comment]
thank you so much :)
